# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :runApp do
    sh("flutter run")
  end

  desc "Build app apk"
  lane :build do
    sh("flutter build apk --release")
  end

  desc "Deploy a new version to Firebase Distribution"
  # fastlane deploy_firebase_distribution version_name:"1.0.2" version_code:3
  lane :deploy_firebase_distribution do |options|
    puts "Options: #{options}"
    version_name = options[:version_name]
    version_code = options[:version_code]

    sh "flutter build apk --build-name=#{version_name} --build-number=#{version_code} --release"

    firebase_app_distribution(
        app: ENV["FIREBASE_APP_ID"],
        firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
        apk_path: "../build/app/outputs/flutter-apk/app-release.apk",
        groups: "tester",
        debug: true,
        release_notes: "Update new code",
    )
  end
end
